theme: minima
title: Lost Cause
author: Alex Fitzgerald
email: alexpfitzgerald@yaho.com
description: > # this means to ignore newlines until "baseurl:"
  I thought I did this already in the index file, but
  this blog is about my thoughts on what I do. I wish
  I had more guidance in my career, so I'm going to
  start writing about what that guidance could have
  looked like

# social links
twitter_username: A_fitzer # DO NOT include the @ character, or else the build will fail!
github_username:  afitzer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
