theme: minima
title: Lost Cause
author: Alex Fitzgerald
email: alexpfitzgerald@yaho.com
description: > # this means to ignore newlines until "baseurl:"
  Hope you are enjoying my page :purple_heart:

# social links
twitter_username: A_fitzer # DO NOT include the @ character, or else the build will fail!
github_username:  afitzer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
